export type Question = { id: string; type: "choice" | "input"; topic: string; prompt: string; options?: string[]; answers: string[]; explanation: string };
export type ProductionKind = "frequency" | "can" | "continuous" | "contrast" | "shop";
export type Lesson = { id: string; unit: string; title: string; minutes: number; goal: string; contextTitle: string; context: string; notice: string; theoryTitle: string; theory: { rule: string; example: string }[]; midTheory: { title: string; text: string; example: string }[]; production: { kind: ProductionKind; prompt: string; scaffold: string; placeholder: string; checks: string[]; sample: string }; questions: Question[] };
const c=(id:string,topic:string,prompt:string,options:string[],answer:string,explanation:string):Question=>({id,type:"choice",topic,prompt,options,answers:[answer],explanation});
const i=(id:string,topic:string,prompt:string,answers:string[],explanation:string):Question=>({id,type:"input",topic,prompt,answers,explanation});

export const lessons: Lesson[] = [
  { id:"4c",unit:"Unit 4C",title:"Habits that last",minutes:35,goal:"Рассказывать о привычках, частоте действий и распорядке дня.",contextTitle:"Elena’s healthy routine",context:"Elena lives in a small town. She walks to work every day and usually cooks dinner at home. She is never late for work. She visits her mother twice a week, but she hardly ever watches TV.",notice:"Сначала поймите общий смысл. Найдите действия и слова, которые показывают, как часто они происходят.",theoryTitle:"Куда ставить слова частотности",theory:[
    {rule:"Перед обычным глаголом",example:"I usually walk to work."},{rule:"После глагола be",example:"She is never late."},{rule:"Конкретная частота — в конце",example:"We exercise twice a week."},{rule:"От 100% к 0%",example:"always → usually → often → sometimes → hardly ever → never"}],midTheory:[
    {title:"Наречие или выражение?",text:"Одно слово (usually, never) ставим рядом с глаголом. Выражение с конкретным периодом ставим в конце.",example:"I often walk. · I walk every day."},
    {title:"Вопрос о частоте",text:"Начинайте с How often, затем используйте обычный порядок вопроса Present Simple.",example:"How often do you exercise?"}],production:{kind:"frequency",prompt:"Напишите 3–4 правдивых предложения о своём обычном дне.",scaffold:"Используйте одно наречие частотности и одно точное выражение частоты.",placeholder:"I usually…\nI never…\nI … twice a week.",checks:["Есть минимум 3 предложения","Есть наречие частотности","Есть точное выражение частоты"],sample:"I usually get up at seven. I never skip breakfast. I go to the gym twice a week."},questions:[
    c("4c1","Reading","How often does Elena visit her mother?",["Every day","Twice a week","Hardly ever","Once a month"],"Twice a week","Найдите в тексте точное выражение частоты."),
    c("4c2","Reading","Which sentence is true?",["Elena often watches TV.","Elena drives to work.","Elena is never late.","Elena never cooks."],"Elena is never late.","Сверяйте утверждение с текстом, а не с личным опытом."),
    i("4c3","Word order","Put the words in order: often / we / dinner / cook / at home",["We often cook dinner at home"],"Often стоит перед смысловым глаголом cook."),
    c("4c4","Expressions","I call my parents ___ (два раза в неделю).",["two week","twice a week","twice week","two times week"],"twice a week","Устойчивая форма: once/twice/three times a week."),
    c("4c5","Months","Which month comes after September?",["August","October","November","December"],"October","Порядок: August, September, October, November."),
    c("4c6","Habits","100% of the time means…",["sometimes","usually","always","hardly ever"],"always","Always обозначает действие, которое происходит всегда."),
    i("4c7","Word order","Correct the sentence: He goes hardly ever to the gym.",["He hardly ever goes to the gym"],"Hardly ever ставим перед обычным глаголом goes."),
    c("4c8","Meaning","Which sentence means примерно один раз в месяц?",["I travel every month.","I travel once a month.","I never travel.","I travel twice a month."],"I travel once a month.","Once a month = один раз в месяц."),
    c("4c9","Routine","Choose the natural answer: How often do you work from home?",["At Monday.","Two a week.","Twice a week.","I am work."],"Twice a week.","How often? требует ответа о частоте."),
    c("4c10","Healthy habits","Which sentence describes a healthy everyday routine?",["I sleep for four hours.","I walk for 30 minutes every day.","I eat fast food every evening.","I hardly ever leave the house."],"I walk for 30 minutes every day.","Every day показывает регулярность, а ходьба — понятная здоровая повседневная привычка.") ]},
  { id:"5a",unit:"Unit 5A",title:"What can you do?",minutes:35,goal:"Говорить об умениях, возможностях, разрешении и просьбах.",contextTitle:"Leo’s audition",context:"Leo is at a talent-show audition. He can cook and play the guitar, but he can’t swim. Before he starts, he asks, “Can I use the piano?” Then he says, “Can you move this chair, please?”",notice:"В тексте can выполняет три задачи: сообщает об умении, спрашивает разрешение и оформляет просьбу.",theoryTitle:"Can / can’t без лишних окончаний",theory:[
    {rule:"Умение",example:"I can swim. / I can’t drive."},{rule:"Вопрос",example:"Can you play the guitar?"},{rule:"Краткий ответ",example:"Yes, I can. / No, I can’t."},{rule:"Просьба и разрешение",example:"Can you help me? Can I sit here?"}],midTheory:[
    {title:"Can не меняется",text:"С I, you, he, she, we, they форма одинаковая. После can всегда идёт начальная форма глагола.",example:"She can sing. · They can sing."},
    {title:"Смысл зависит от подлежащего",text:"Can I…? обычно спрашивает разрешение. Can you…? часто является просьбой.",example:"Can I come in? · Can you open the door?"}],production:{kind:"can",prompt:"Напишите мини-профиль для конкурса талантов из 4 предложений.",scaffold:"Укажите два умения, одно неумение и добавьте один вопрос организатору.",placeholder:"I can…\nI can…\nI can’t…\nCan I…?",checks:["Есть минимум 4 предложения","Есть can и can’t/cannot","Есть вопрос с Can I…? или Can you…?"],sample:"I can sing. I can play the guitar. I can’t dance. Can I use the piano?"},questions:[
    c("5a1","Reading","What can’t Leo do?",["Cook","Play the guitar","Swim","Move a chair"],"Swim","Can’t показывает отсутствие умения."),
    c("5a2","Reading","Why does Leo say “Can I use the piano?”",["He describes an ability.","He asks for permission.","He gives an order.","He says he can’t play."],"He asks for permission.","Can I…? используется, когда говорящий просит разрешение для себя."),
    c("5a3","Question","Choose the correct question.",["Do you can cook?","Can you cook?","Can cook you?","Are you can cook?"],"Can you cook?","Вопрос: Can + subject + verb?"),
    c("5a4","Short answer","Can Marta sing? — Yes, ___.",["she does","she is","she can","she sings"],"she can","Краткий ответ повторяет can."),
    c("5a5","Request","You need help with a bag. What do you say?",["Can you help me?","You can help?","Do help me can?","Can I helping?"],"Can you help me?","Can you…? — вежливая простая просьба."),
    c("5a6","Permission","Ask for permission to open the window.",["Can you open the window?","Can I open the window?","I can open window?","Do I can open it?"],"Can I open the window?","Can I…? спрашивает разрешение для себя."),
    c("5a7","Verb phrases","Choose the natural phrase.",["do a photo","make tennis","play the guitar","go TV"],"play the guitar","С музыкальными инструментами используем play."),
    c("5a8","Verb phrases","Choose the natural phrase.",["listen music","listen to music","hear to music","play music to"],"listen to music","После listen нужен предлог to."),
    i("5a9","Word order","Put in order: well / can / very / dance / she",["She can dance very well"],"Наречие very well обычно ставится после основного глагола."),
    c("5a10","Meaning","Which sentence is a prohibition?",["You can park here.","You can’t park here.","Can you park here?","I can park well."],"You can’t park here.","Can’t также означает, что действие не разрешено.") ]},
  { id:"5b",unit:"Unit 5B",title:"What’s happening now?",minutes:38,goal:"Описывать действия, которые происходят прямо сейчас, и говорить о шуме.",contextTitle:"A noisy evening",context:"It’s eleven o’clock. A baby is crying upstairs, a dog is barking outside, and the neighbours are playing loud music. Marta isn’t sleeping. She is writing a message to the building manager.",notice:"Ищите две части формы: am/is/are и глагол с -ing. Они показывают, что ситуация происходит сейчас.",theoryTitle:"Present Continuous: be + verb-ing",theory:[
    {rule:"Форма",example:"am / is / are + verb-ing"},{rule:"Сейчас",example:"They’re having a party now."},{rule:"Отрицание",example:"He isn’t sleeping."},{rule:"Вопрос",example:"Are the neighbours arguing?"}],midTheory:[
    {title:"Не забывайте be",text:"Форма только с -ing неполная. Перед смысловым глаголом обязательно нужны am, is или are.",example:"They are talking. (не They talking)"},
    {title:"Как образовать -ing",text:"Обычно добавляем -ing; конечную e убираем. В коротких словах иногда удваиваем согласную.",example:"work → working · write → writing · sit → sitting"}],production:{kind:"continuous",prompt:"Представьте, что вы смотрите из окна. Опишите 3 действия, которые происходят сейчас.",scaffold:"Используйте разные подлежащие и полную форму am/is/are + verb-ing.",placeholder:"A woman is…\nTwo children are…\nI am…",checks:["Есть минимум 3 предложения","Есть минимум 3 формы be + verb-ing","Использованы разные подлежащие"],sample:"A woman is walking her dog. Two children are playing football. I am watching them."},questions:[
    c("5b1","Reading","Which sound comes from outside?",["A baby is crying.","A dog is barking.","Marta is writing.","A manager is sleeping."],"A dog is barking.","В тексте outside относится к собаке."),
    c("5b2","Reading","What is Marta doing?",["She is sleeping.","She is playing music.","She is writing a message.","She is crying."],"She is writing a message.","Найдите действие после She is…"),
    c("5b3","Negative","Choose the correct sentence.",["He not sleeping.","He isn’t sleeping.","He doesn’t sleeping.","He no sleep."],"He isn’t sleeping.","Отрицание образует be + not + verb-ing."),
    c("5b4","Question","___ you watching TV?",["Do","Can","Are","Is"],"Are","Вопрос начинается с формы be: Are you…?"),
    i("5b5","Short answer","Is she working? — No, ___.",["she isn't","she is not"],"В кратком ответе используем ту же форму be."),
    c("5b6","Noise","Which sound does a dog make?",["It argues.","It barks.","It practises.","It pings."],"It barks.","A dog barks; a phone pings."),
    c("5b7","Noise","Your neighbours’ music is very loud. They are…",["making a lot of noise","doing a lot of noise","having a noise","barking music"],"making a lot of noise","Устойчивая фраза: make a lot of noise."),
    i("5b8","-ing form","Complete: I am ___ (write) an email now.",["writing"],"Write → writing: конечная e исчезает."),
    c("5b9","Situation","Listen! Someone ___ the piano.",["practises","is practising","can practises","practise"],"is practising","Listen! показывает, что действие происходит сейчас."),
    c("5b10","Conversation","What are you doing? — ___",["I work every day.","I’m cooking dinner.","Yes, I do.","At seven."],"I’m cooking dinner.","Вопрос о текущем действии требует Present Continuous.") ]},
  { id:"5c",unit:"Unit 5C",title:"Every day or right now?",minutes:40,goal:"Различать привычки и действия сейчас, говорить о погоде и писать короткий пост.",contextTitle:"Sofia’s week in London",context:"Sofia usually works from home in Madrid, but this week she is staying in London. She takes the metro every day. Right now, she is sitting in a café because it is raining outside.",notice:"Разделите факты на две группы: обычная жизнь и временная ситуация сейчас. Маркеры usually/every day и this week/right now помогут.",theoryTitle:"Привычка или действие сейчас?",theory:[
    {rule:"Обычно / регулярно",example:"I take the bus every day."},{rule:"Прямо сейчас",example:"I’m walking today."},{rule:"Маркеры Simple",example:"usually, every day, on Mondays"},{rule:"Маркеры Continuous",example:"now, today, at the moment"}],midTheory:[
    {title:"Смотрите на смысл",text:"Today может описывать временную ситуацию, а every day — регулярную привычку. Спросите: это обычно или сейчас?",example:"She works at home. · Today she is working in a café."},
    {title:"Как говорить о погоде",text:"После It’s используйте прилагательное; для осадков — глагол с -ing.",example:"It’s sunny. · It’s raining."}],production:{kind:"contrast",prompt:"Напишите короткий пост из 4 предложений о поездке или необычном дне.",scaffold:"Сравните обычную жизнь с тем, что происходит сегодня, и упомяните погоду.",placeholder:"I usually…\nThis week I’m…\nRight now…\nIt’s…",checks:["Есть привычка с маркером частотности","Есть действие сейчас с be + verb-ing","Упомянута погода"],sample:"I usually work at home. This week I’m staying in London. Right now I’m drinking coffee. It’s raining."},questions:[
    c("5c1","Reading","Where does Sofia usually work?",["In a London café","From home in Madrid","On the metro","In a hotel"],"From home in Madrid","Usually вводит её обычную ситуацию."),
    c("5c2","Reading","Why is she sitting in a café now?",["She works there every day.","It is raining.","The metro is closed.","She lives there."],"It is raining.","Причина прямо дана в тексте после because."),
    c("5c3","Tenses","Look! It ___.",["snows","is snowing","snow","snowing"],"is snowing","Look! указывает на действие прямо сейчас."),
    c("5c4","Tenses","We ___ this café every Saturday.",["are visiting","visits","visit","visiting"],"visit","Every Saturday — регулярное действие."),
    i("5c5","Form","Complete: What ___ you doing at the moment?",["are"],"В Present Continuous вопрос строится с am/is/are."),
    c("5c6","Weather","The sun is shining. It’s ___.",["foggy","sunny","snowy","windy"],"sunny","Sunny описывает солнечную погоду."),
    c("5c7","Weather","You can’t see far because it’s ___.",["foggy","hot","dry","sunny"],"foggy","Foggy = туманно."),
    c("5c8","Seasons","In Britain, December is in ___.",["spring","summer","autumn","winter"],"winter","December, January and February are winter months."),
    i("5c9","Writing","Complete the holiday post: We ___ (stay) in London this week.",["are staying","'re staying","re staying"],"Временная ситуация this week — Present Continuous."),
    c("5c10","Writing","Choose the best holiday update.",["I usually visit a museum now.","I’m sitting in a café now. It’s raining outside.","I am go to London every today.","Now I sit usually outside."],"I’m sitting in a café now. It’s raining outside.","Оба действия происходят сейчас, поэтому нужен Present Continuous.") ]},
  { id:"practical",unit:"Practical English",title:"Shopping in London",minutes:42,goal:"Покупать одежду, понимать цены и уверенно использовать ключевые темы курса.",contextTitle:"In a clothes shop",context:"Assistant: Can I help you? Marta: Yes, I’m looking for a sweater. Assistant: What size are you? Marta: Medium. Can I try this blue one on? Assistant: Of course. The changing rooms are over there. Marta: Great. How much is it?",notice:"Определите роли говорящих и цель каждой реплики: помощь, размер, примерка, место и цена.",theoryTitle:"Диалог в магазине: готовые опоры",theory:[
    {rule:"Предложить помощь",example:"Can I help you?"},{rule:"Примерить",example:"Can I try it on?"},{rule:"Уточнить размер",example:"What size is this?"},{rule:"This / these",example:"this jacket · these trousers"}],midTheory:[
    {title:"It или them?",text:"После try … on используйте it для одной вещи и them для множественного числа.",example:"Can I try it on? · Can I try them on?"},
    {title:"Как назвать цену",text:"£29.99 читается как twenty-nine pounds ninety-nine. В разговоре слово pence часто опускают.",example:"It’s twenty-nine pounds ninety-nine."}],production:{kind:"shop",prompt:"Напишите мини-диалог в магазине: минимум 4 реплики.",scaffold:"Попросите вещь, назовите размер, попросите примерить и спросите цену.",placeholder:"Assistant: Can I help you?\nYou: I’m looking for…\nAssistant: …\nYou: Can I try…?",checks:["Есть минимум 4 реплики","Есть минимум 2 магазинные фразы","Есть одежда и this/these или it/them"],sample:"Assistant: Can I help you?\nCustomer: I’m looking for a jacket.\nAssistant: What size are you?\nCustomer: Medium. Can I try this one on?\nCustomer: How much is it?"},questions:[
    c("pe1","Reading","What is Marta looking for?",["A skirt","A sweater","Shoes","Jeans"],"A sweater","Фраза I’m looking for… называет нужный товар."),
    c("pe2","Reading","What size does Marta need?",["Small","Medium","Large","Extra large"],"Medium","Ответ идёт сразу после вопроса What size are you?"),
    c("pe3","This / these","Can I try ___ jacket on?",["these","those","this","they"],"this","Jacket — единственное число, поэтому this."),
    c("pe4","Shopping","Shop assistant: Can I help you? Customer: ___",["Yes, I’m looking for a sweater.","I help you.","Yes, I am look.","No, I can sweater."],"Yes, I’m looking for a sweater.","Это естественный ответ покупателя."),
    c("pe5","Shopping","Ask where you can try clothes on.",["Where are the changing rooms?","How are the rooms changing?","Where I change?","Can rooms?"],"Where are the changing rooms?","Changing rooms — примерочные."),
    c("pe6","Shopping","The sweater is too small. What do you ask?",["Do you have it in a larger size?","Is it more small?","Can it large?","Have you size big?"],"Do you have it in a larger size?","Так вежливо спрашивают другой размер."),
    c("pe7","Price","£29.99 is…",["twenty-nine pounds ninety-nine","two nine pounds","twenty-nine pence","ninety-nine pounds twenty-nine"],"twenty-nine pounds ninety-nine","Сначала называем фунты, затем пенсы."),
    c("pe8","Social English","You look great! — ___",["Thanks!","Yes, I look.","Great you.","I can great."],"Thanks!","На комплимент естественно ответить Thanks."),
    c("pe9","Final: frequency","Choose the correct sentence.",["I am often tired after work.","I often am tired after work."],"I am often tired after work.","С be наречие частотности ставим после глагола."),
    c("pe10","Final: can","___ I pay by card?",["Do","Am","Can","Have"],"Can","Can I…? — просьба о разрешении/возможности."),
    c("pe11","Final: now","The assistant ___ another customer now.",["helps","is helping","help","can helping"],"is helping","Now указывает на Present Continuous."),
    c("pe12","Final: contrast","I usually ___ jeans, but today I ___ a skirt.",["wear / am wearing","am wearing / wear","wears / wearing","wear / wear"],"wear / am wearing","Привычка — Present Simple; сегодня — Present Continuous.") ]}
];
